export const cartTypes = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CONFIRM_ORDER: "CONFIRM_ORDER",
    REMOVE_ORDER: "REMOVE_ORDER",
    INCREASE_CART: "INCREASE_CART",
    DECREASE_CART: "DECREASE_CART"
}